/**
 * Throwaway email providers: addresses that exist for minutes, made to be
 * thrown away after one signup.
 *
 * Source: a hand-checked subset of the community blocklist at
 * https://github.com/disposable-email-domains/disposable-email-domains
 * (CC0, `disposable_email_blocklist.conf`), snapshot taken 2026-09-17, keeping
 * the providers that turn up in free-trial abuse and dropping anything that
 * doubles as a real mailbox. Shipped in the repo and never fetched at runtime:
 * a signup must not depend on a third-party file being reachable, and a list
 * that changes under us would start refusing people without a commit saying so.
 *
 * To update: add or remove lines here, run `npm run check:abuse`, commit. A
 * false positive for one person is fixed without a deploy: staff allow the
 * address in the sales console's Abuse review.
 *
 * Matching is by domain and every parent domain, so `x.mailinator.com` is
 * caught by `mailinator.com`. Lower case, no leading dot.
 */
export const DISPOSABLE_DOMAINS: readonly string[] = [
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.co.uk",
  "20minutemail.com",
  "anonbox.net",
  "armyspy.com",
  "binkmail.com",
  "bobmail.info",
  "burnermail.io",
  "byom.de",
  "chammy.info",
  "cuvox.de",
  "dayrep.com",
  "deadaddress.com",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "dispostable.com",
  "dodgit.com",
  "dropmail.me",
  "einrot.com",
  "emailondeck.com",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "fakeinbox.com",
  "fakemail.net",
  "fleckens.hu",
  "getairmail.com",
  "getnada.com",
  "gishpuppy.com",
  "grr.la",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "gustr.com",
  "harakirimail.com",
  "hmamail.com",
  "incognitomail.com",
  "incognitomail.org",
  "inboxbear.com",
  "inboxkitten.com",
  "jetable.org",
  "jourrapide.com",
  "kasmail.com",
  "linshiyouxiang.net",
  "mail-temp.com",
  "mail.tm",
  "mail7.io",
  "mailcatch.com",
  "maildrop.cc",
  "mailexpire.com",
  "mailforspam.com",
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "mailnesia.com",
  "mailnull.com",
  "mailpoof.com",
  "mailsac.com",
  "mailtemp.info",
  "meltmail.com",
  "minuteinbox.com",
  "moakt.com",
  "mohmal.com",
  "mintemail.com",
  "mt2015.com",
  "mytemp.email",
  "mytrashmail.com",
  "nada.email",
  "no-spam.ws",
  "nowmymail.com",
  "objectmail.com",
  "one-time.email",
  "onewaymail.com",
  "pokemail.net",
  "proxymail.eu",
  "rcpt.at",
  "rhyta.com",
  "sharklasers.com",
  "shieldemail.com",
  "slippery.email",
  "snapmail.cc",
  "sofort-mail.de",
  "spam4.me",
  "spambog.com",
  "spambox.us",
  "spamdecoy.net",
  "spamex.com",
  "spamfree24.org",
  "spamherelots.com",
  "spaml.com",
  "superrito.com",
  "teleworm.us",
  "temp-mail.io",
  "temp-mail.org",
  "tempail.com",
  "tempemail.com",
  "tempinbox.com",
  "tempmail.com",
  "tempmail.dev",
  "tempmail.net",
  "tempmail.plus",
  "tempmailo.com",
  "tempr.email",
  "temporary-mail.net",
  "thankyou2010.com",
  "throwawaymail.com",
  "tmail.ws",
  "tmailor.com",
  "tmpeml.com",
  "tmpmail.net",
  "tmpmail.org",
  "trash-mail.com",
  "trashmail.com",
  "trashmail.de",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trbvm.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "zetmail.com",
];
