/**
 * The backgrounds a venue can put behind its video receptionist.
 *
 * All original: generated by `scripts/build-video-backgrounds.ts` into
 * `public/video/backgrounds/` (no stock photography, nothing to license).
 * Plain data, safe for the browser bundle.
 *
 * A background only shows where Tavus can give the face a green screen:
 * `properties.apply_greenscreen` on Create Conversation, which "is not
 * currently available with Phoenix-4.5 faces"
 * (https://docs.tavus.io/sections/conversational-video-interface/conversation/customizations/background-customizations).
 * On any other face, and whenever the browser cannot key the stream fast
 * enough, the call shows the face's own room (`original`).
 */

export interface VideoBackground {
  id: string;
  name: string;
  /** A path on this app, or empty for the face's own room. */
  src: string;
  /** Mostly light or dark: the circle's ring and the pills pick contrast from it. */
  tone: "light" | "dark";
}

export const ORIGINAL_BACKGROUND_ID = "original";
export const DEFAULT_BACKGROUND_ID = "belline-light";

export const VIDEO_BACKGROUNDS: readonly VideoBackground[] = [
  { id: "belline-light", name: "Belline light", src: "/video/backgrounds/belline-light.jpg", tone: "light" },
  { id: "studio-grey", name: "Studio grey", src: "/video/backgrounds/studio-grey.jpg", tone: "light" },
  { id: "warm-lounge", name: "Warm lounge", src: "/video/backgrounds/warm-lounge.jpg", tone: "light" },
  { id: "evening-navy", name: "Evening navy", src: "/video/backgrounds/evening-navy.jpg", tone: "dark" },
  { id: "plain-white", name: "Plain white", src: "/video/backgrounds/plain-white.jpg", tone: "light" },
  { id: ORIGINAL_BACKGROUND_ID, name: "The face's own room", src: "", tone: "dark" },
] as const;

export function videoBackground(id: string | null | undefined): VideoBackground | undefined {
  return VIDEO_BACKGROUNDS.find((b) => b.id === id);
}

export function isKnownBackground(id: unknown): id is string {
  return typeof id === "string" && VIDEO_BACKGROUNDS.some((b) => b.id === id);
}
