"use client";

import { useCallback, useEffect, useRef, useState } from "react";

/**
 * The chat panel a website visitor sees.
 *
 * Written as one component with its own stylesheet because it is the one screen
 * in this product that renders inside somebody else's page. It shares no CSS
 * with the dashboard on purpose: a change to a dashboard token must not be able
 * to alter what a customer's customer sees on a customer's website.
 *
 * Three things here are decisions rather than defaults.
 *
 * **The opening line is local.** It costs nothing, arrives instantly, and is
 * not recorded — the thread in the inbox begins with what the visitor actually
 * asked. A greeting generated by a model would be a model call, a second of
 * waiting, and a row of transcript that says nothing.
 *
 * **Staff replies arrive by polling.** Four seconds, and only while the panel is
 * open and visible. A socket would be fewer requests and one more thing that can
 * be half-connected; the inbox writing a row and being finished is worth more
 * than the requests it saves.
 *
 * **Belline and a colleague look the same to the visitor.** Both are the
 * business. The distinction is real, it matters, and it is in the inbox where a
 * colleague can see who said what — showing it here would only invite a visitor
 * to re-read half the conversation wondering which half to trust.
 */

type Line = {
  id: number;
  who: "you" | "them" | "note";
  text: string;
  at: string;
};

type Status = "AI_ACTIVE" | "HANDOFF_REQUESTED" | "HUMAN_ACTIVE" | "CLOSED";

const POLL_MS = 4000;

export default function Chat({
  embedKey,
  freshToken,
  venueName,
  agentName,
  voiceHref,
}: {
  embedKey: string;
  freshToken: string;
  venueName: string;
  agentName: string;
  voiceHref?: string;
}) {
  const [lines, setLines] = useState<Line[]>([]);
  const [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<Status>("AI_ACTIVE");
  const [trouble, setTrouble] = useState<string | null>(null);

  const token = useRef<string>(freshToken);
  const lastId = useRef(0);
  const foot = useRef<HTMLDivElement | null>(null);

  /**
   * Keep the conversation across a reload.
   *
   * `sessionStorage`, not `localStorage`: a conversation is this visit, and a
   * booking somebody half-made three weeks ago should not reappear when they
   * come back to compare prices. Wrapped because a browser set to block site
   * data throws on the accessor itself rather than returning nothing.
   */
  useEffect(() => {
    const slot = `belline:chat:${embedKey}`;
    try {
      const kept = sessionStorage.getItem(slot);
      if (kept) token.current = kept;
      else sessionStorage.setItem(slot, freshToken);
    } catch {
      /* a conversation that does not survive a reload is still a conversation */
    }
  }, [embedKey, freshToken]);

  const absorb = useCallback(
    (payload: {
      messages?: { id: number; sender: string; body: string; createdAt: string }[];
      status?: Status;
      lastId?: number;
    }) => {
      if (payload.status) setStatus(payload.status);
      if (typeof payload.lastId === "number" && payload.lastId > lastId.current) {
        lastId.current = payload.lastId;
      }
      const incoming = (payload.messages ?? []).filter((m) => m.body);
      if (!incoming.length) return;
      setLines((prev) => {
        const known = new Set(prev.map((l) => l.id));
        const added = incoming
          .filter((m) => !known.has(m.id))
          .map((m) => ({
            id: m.id,
            who: m.sender === "system" ? ("note" as const) : ("them" as const),
            text: m.body,
            at: m.createdAt,
          }));
        return added.length ? [...prev, ...added] : prev;
      });
    },
    [],
  );

  // Anything said while nobody was asking — a colleague's reply from the inbox.
  useEffect(() => {
    if (status === "CLOSED") return;
    let stop = false;

    async function look() {
      if (stop || document.hidden) return;
      try {
        const res = await fetch(
          `/api/webchat/${encodeURIComponent(embedKey)}?token=${encodeURIComponent(
            token.current,
          )}&after=${lastId.current}`,
        );
        if (res.ok) absorb(await res.json());
      } catch {
        // A failed poll is not worth telling a visitor about. The next one is
        // four seconds away, and the thing they are waiting for is a person.
      }
    }

    const timer = setInterval(look, POLL_MS);
    return () => {
      stop = true;
      clearInterval(timer);
    };
  }, [embedKey, absorb, status]);

  useEffect(() => {
    foot.current?.scrollIntoView({ block: "end", behavior: "smooth" });
  }, [lines, busy]);

  async function send() {
    const text = draft.trim();
    if (!text || busy) return;

    setDraft("");
    setTrouble(null);
    // Optimistic, and negative ids so it can never collide with a row's. The
    // visitor's own words appearing instantly is the difference between a chat
    // and a form.
    const mine: Line = { id: -Date.now(), who: "you", text, at: new Date().toISOString() };
    setLines((prev) => [...prev, mine]);
    setBusy(true);

    const clientId = messageId();
    try {
      const res = await fetch(`/api/webchat/${encodeURIComponent(embedKey)}`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ token: token.current, text, clientId }),
      });

      if (res.status === 401) {
        // The token expired while the panel sat open. Reloading mints a new one,
        // which is what the visitor would try anyway.
        setTrouble("This conversation timed out. Reload the page to start again.");
        return;
      }
      if (res.status === 429) {
        // A turn for this visitor is already running — they pressed send twice
        // while Belline was thinking. Their message is being answered, so an
        // error would be a lie about the one thing they can see. Say nothing;
        // the poll four seconds away collects the reply.
        return;
      }
      if (!res.ok) {
        setTrouble("That didn't send. Try again in a moment.");
        return;
      }
      absorb(await res.json());
    } catch {
      setTrouble("That didn't send. Try again in a moment.");
    } finally {
      setBusy(false);
    }
  }

  const waiting = status === "HANDOFF_REQUESTED";
  const withPerson = status === "HUMAN_ACTIVE";

  return (
    <div className="bl-wrap">
      <style>{CSS}</style>

      <header>
        <span className="bl-mark" aria-hidden="true">
          <Bubble />
        </span>
        <span className="bl-who">
          <strong>{venueName}</strong>
          <em>
            {withPerson
              ? "You're talking to the team"
              : waiting
                ? "Passing you to the team"
                : `${agentName} · replies in seconds`}
          </em>
        </span>
        {voiceHref && (
          <a className="bl-swap" href={voiceHref}>
            Rather talk?
          </a>
        )}
      </header>

      <div className="bl-log" role="log" aria-live="polite">
        <p className="bl-opener">
          Hi — I&rsquo;m {agentName} at {venueName}. Ask me anything, or tell me what you&rsquo;d
          like to book.
        </p>

        {lines.map((l) =>
          l.who === "note" ? (
            <p key={l.id} className="bl-note">
              {l.text}
            </p>
          ) : (
            <div key={l.id} className={`bl-line bl-${l.who}`}>
              <p>{l.text}</p>
            </div>
          ),
        )}

        {busy && (
          <div className="bl-line bl-them bl-thinking" aria-label="typing">
            <p>
              <i />
              <i />
              <i />
            </p>
          </div>
        )}

        {(waiting || withPerson) && (
          <p className="bl-note">
            Someone from the team is picking this up. Anything you add here will reach them.
          </p>
        )}

        <div ref={foot} />
      </div>

      {trouble && <p className="bl-trouble">{trouble}</p>}

      <form
        onSubmit={(e) => {
          e.preventDefault();
          void send();
        }}
      >
        <textarea
          rows={1}
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={(e) => {
            // Enter sends, shift+enter breaks the line. The convention every
            // other chat has, and getting it wrong makes the panel feel broken.
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              void send();
            }
          }}
          placeholder="Type your message"
          aria-label="Your message"
          maxLength={1000}
        />
        <button type="submit" disabled={busy || !draft.trim()} aria-label="Send">
          <Send />
        </button>
      </form>
    </div>
  );
}

function messageId(): string {
  // Enough to be unique per visitor's session, which is all the dedup key needs
  // to be — it is scoped to one conversation by the index it lands in.
  return `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * The mark.
 *
 * A bell inside a speech bubble: the same bell as everywhere else, so a visitor
 * who has seen the button knows what opened, in the one shape that says this one
 * is for typing.
 */
function Bubble() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M3 11.2C3 6.9 7.03 3.5 12 3.5s9 3.4 9 7.7c0 4.3-4.03 7.7-9 7.7a11 11 0 0 1-2.4-.26L5.4 20.5l.5-3.2A7.7 7.7 0 0 1 3 11.2Z"
        fill="currentColor"
        opacity=".16"
      />
      <path
        d="M3 11.2C3 6.9 7.03 3.5 12 3.5s9 3.4 9 7.7c0 4.3-4.03 7.7-9 7.7a11 11 0 0 1-2.4-.26L5.4 20.5l.5-3.2A7.7 7.7 0 0 1 3 11.2Z"
        stroke="currentColor"
        strokeWidth="1.4"
        strokeLinejoin="round"
      />
      <circle cx="12" cy="7.3" r="1.05" fill="currentColor" />
      <path d="M8.6 13.2a3.4 3.4 0 0 1 6.8 0Z" fill="currentColor" />
      <rect x="7.7" y="13.9" width="8.6" height="1.4" rx=".7" fill="currentColor" />
    </svg>
  );
}

function Send() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M4 12h13M11.5 6.5 17.5 12l-6 5.5"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/**
 * Scoped by being the only stylesheet on the page.
 *
 * The panel is a whole document inside an iframe, so there is nothing to collide
 * with and no cascade to defend against — which is why these are element
 * selectors rather than a class system that would only exist to look careful.
 */
const CSS = `
:root { color-scheme: dark }
* { box-sizing: border-box }
html, body { margin: 0; height: 100% }
body { background: #14110D }

.bl-wrap {
  height: 100dvh;
  display: grid;
  grid-template-rows: auto 1fr auto;
  background: #14110D;
  color: #FBF9F5;
  font: 400 15px/1.55 "Instrument Sans", ui-sans-serif, system-ui, -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
}

.bl-wrap header {
  display: flex;
  align-items: center;
  gap: 11px;
  padding: 14px 16px;
  border-bottom: 1px solid rgba(251,249,245,.1);
}
.bl-mark { display: grid; place-items: center; width: 32px; height: 32px; flex: none;
  border-radius: 999px; background: rgba(232,220,198,.12); color: #E8DCC6 }
.bl-mark svg { width: 19px; height: 19px; display: block }
.bl-who { display: grid; min-width: 0 }
.bl-who strong { font-weight: 600; font-size: 14.5px; letter-spacing: -.01em;
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis }
.bl-who em { font-style: normal; font-size: 12.5px; color: rgba(251,249,245,.62) }
.bl-swap {
  margin-left: auto; flex: none; color: #E8DCC6; text-decoration: none;
  font-size: 12.5px; padding: 6px 11px; border-radius: 999px;
  border: 1px solid rgba(232,220,198,.3);
}
.bl-swap:hover { background: rgba(232,220,198,.1) }

.bl-log { overflow-y: auto; padding: 18px 16px 6px; display: grid; align-content: start; gap: 10px }

.bl-opener { margin: 0 0 4px; font-size: 14.5px; color: rgba(251,249,245,.72); max-width: 34ch }

.bl-line { display: flex }
.bl-line p {
  margin: 0; padding: 9px 13px; max-width: 84%;
  border-radius: 15px; font-size: 14.5px; white-space: pre-wrap; overflow-wrap: anywhere;
}
.bl-line.bl-them { justify-content: flex-start }
.bl-line.bl-them p { background: #221D17; border-bottom-left-radius: 5px }
.bl-line.bl-you { justify-content: flex-end }
.bl-line.bl-you p { background: #E8DCC6; color: #14110D; border-bottom-right-radius: 5px }

.bl-note {
  margin: 2px auto; padding: 6px 12px; font-size: 12.5px; text-align: center;
  color: rgba(251,249,245,.6); background: rgba(251,249,245,.05); border-radius: 999px;
}

.bl-thinking p { display: flex; gap: 4px; padding: 13px }
.bl-thinking i { width: 5px; height: 5px; border-radius: 999px; background: rgba(251,249,245,.5);
  animation: pulse 1.1s infinite }
.bl-thinking i:nth-child(2) { animation-delay: .15s }
.bl-thinking i:nth-child(3) { animation-delay: .3s }
@keyframes pulse { 0%,60%,100% { opacity: .3 } 30% { opacity: 1 } }

.bl-trouble { margin: 0; padding: 8px 16px; font-size: 13px; color: #F0B7A4 }

.bl-wrap form { display: flex; gap: 8px; align-items: end; padding: 12px 14px 14px;
  border-top: 1px solid rgba(251,249,245,.1) }
.bl-wrap textarea {
  flex: 1; resize: none; min-height: 42px; max-height: 120px;
  padding: 11px 13px; border-radius: 13px; border: 1px solid rgba(251,249,245,.16);
  background: #1C1813; color: #FBF9F5; font: inherit; font-size: 14.5px;
}
.bl-wrap textarea::placeholder { color: rgba(251,249,245,.42) }
/* Der Rahmen des Dashboards legt beim Fokus noch einen blassen Ring auf jedes
   Textfeld. Zusammen mit dem Umriss unten sind das zwei Ringe um dasselbe
   Feld — hier gilt nur der eine. */
.bl-wrap textarea:focus { box-shadow: none; border-color: rgba(251,249,245,.16) }
.bl-wrap textarea:focus-visible, .bl-wrap button:focus-visible, .bl-swap:focus-visible {
  outline: 2px solid #E8DCC6; outline-offset: 2px;
}
.bl-wrap button {
  flex: none; width: 42px; height: 42px; border: 0; border-radius: 13px;
  background: #E8DCC6; color: #14110D; cursor: pointer; display: grid; place-items: center;
}
.bl-wrap button svg { width: 21px; height: 21px }
.bl-wrap button:disabled { opacity: .4; cursor: default }

@media (prefers-reduced-motion: reduce) { .bl-thinking i { animation: none; opacity: .6 } }
`;
