"use client";

import { useCallback, useEffect, useRef, useState } from "react";

/**
 * The chat panel a website visitor sees.
 *
 * Written as one component with its own stylesheet because it is the one screen
 * in this product that renders inside somebody else's page. It shares no CSS
 * with the dashboard on purpose: a change to a dashboard token must not be able
 * to alter what a customer's customer sees on a customer's website.
 *
 * Three things here are decisions rather than defaults.
 *
 * **The opening line is local.** It costs nothing, arrives instantly, and is
 * not recorded — the thread in the inbox begins with what the visitor actually
 * asked. A greeting generated by a model would be a model call, a second of
 * waiting, and a row of transcript that says nothing.
 *
 * **Staff replies arrive by polling.** Four seconds, and only while the panel is
 * open and visible. A socket would be fewer requests and one more thing that can
 * be half-connected; the inbox writing a row and being finished is worth more
 * than the requests it saves.
 *
 * **Belline and a colleague look the same to the visitor.** Both are the
 * business. The distinction is real, it matters, and it is in the inbox where a
 * colleague can see who said what — showing it here would only invite a visitor
 * to re-read half the conversation wondering which half to trust.
 */

type Line = {
  id: number;
  who: "you" | "them" | "note";
  text: string;
  at: string;
  /** Spoken rather than typed: how long, and whether the words are in yet. */
  voice?: { seconds: number; pending?: boolean };
};

type Status = "AI_ACTIVE" | "HANDOFF_REQUESTED" | "HUMAN_ACTIVE" | "CLOSED";

const POLL_MS = 4000;

/**
 * The voice note.
 *
 * Hold the microphone, talk, let go — the way WhatsApp settled it, because
 * that is the gesture every visitor's thumb already knows. A quick tap is
 * not a recording; it shows the hint instead, which is also WhatsApp's
 * answer to the same mistake. Sliding off the button before letting go
 * throws the note away.
 *
 * What comes back is words, not audio: the note is transcribed on the way in
 * and Belline replies in writing, like everything else here. The visitor
 * chose the quiet channel; a spoken reply would break that.
 */
const NOTE_MAX_SECONDS = 60;
/** Shorter than this was a tap, not a note. */
const NOTE_MIN_MS = 600;

/** What the browser can record. Chrome and Firefox make Opus; Safari makes AAC. */
function recordingMime(): string | null {
  if (typeof MediaRecorder === "undefined") return null;
  for (const type of ["audio/webm;codecs=opus", "audio/ogg;codecs=opus", "audio/mp4", "audio/webm"]) {
    if (MediaRecorder.isTypeSupported(type)) return type;
  }
  return null;
}

export default function Chat({
  embedKey,
  freshToken,
  venueName,
  agentName,
  voiceHref,
}: {
  embedKey: string;
  freshToken: string;
  venueName: string;
  agentName: string;
  voiceHref?: string;
}) {
  const [lines, setLines] = useState<Line[]>([]);
  const [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<Status>("AI_ACTIVE");
  const [trouble, setTrouble] = useState<string | null>(null);
  /** Seconds into a recording, or null when not recording. */
  const [recording, setRecording] = useState<number | null>(null);
  const [hint, setHint] = useState<string | null>(null);
  const [canRecord, setCanRecord] = useState(false);

  const token = useRef<string>(freshToken);
  const lastId = useRef(0);
  const foot = useRef<HTMLDivElement | null>(null);
  const rec = useRef<{
    recorder: MediaRecorder;
    stream: MediaStream;
    chunks: Blob[];
    startedAt: number;
    tick: ReturnType<typeof setInterval>;
    stopAt: ReturnType<typeof setTimeout>;
    /** Set when the pointer slid off before release, or the note was too short. */
    discard: boolean;
  } | null>(null);

  useEffect(() => {
    setCanRecord(Boolean(recordingMime() && navigator.mediaDevices?.getUserMedia));
  }, []);

  /**
   * Keep the conversation across a reload.
   *
   * `sessionStorage`, not `localStorage`: a conversation is this visit, and a
   * booking somebody half-made three weeks ago should not reappear when they
   * come back to compare prices. Wrapped because a browser set to block site
   * data throws on the accessor itself rather than returning nothing.
   */
  useEffect(() => {
    const slot = `belline:chat:${embedKey}`;
    try {
      const kept = sessionStorage.getItem(slot);
      if (kept) token.current = kept;
      else sessionStorage.setItem(slot, freshToken);
    } catch {
      /* a conversation that does not survive a reload is still a conversation */
    }
  }, [embedKey, freshToken]);

  const absorb = useCallback(
    (payload: {
      messages?: { id: number; sender: string; body: string; createdAt: string }[];
      status?: Status;
      lastId?: number;
    }) => {
      if (payload.status) setStatus(payload.status);
      if (typeof payload.lastId === "number" && payload.lastId > lastId.current) {
        lastId.current = payload.lastId;
      }
      const incoming = (payload.messages ?? []).filter((m) => m.body);
      if (!incoming.length) return;
      setLines((prev) => {
        const known = new Set(prev.map((l) => l.id));
        const added = incoming
          .filter((m) => !known.has(m.id))
          .map((m) => ({
            id: m.id,
            who: m.sender === "system" ? ("note" as const) : ("them" as const),
            text: m.body,
            at: m.createdAt,
          }));
        return added.length ? [...prev, ...added] : prev;
      });
    },
    [],
  );

  // Anything said while nobody was asking — a colleague's reply from the inbox.
  useEffect(() => {
    if (status === "CLOSED") return;
    let stop = false;

    async function look() {
      if (stop || document.hidden) return;
      try {
        const res = await fetch(
          `/api/webchat/${encodeURIComponent(embedKey)}?token=${encodeURIComponent(
            token.current,
          )}&after=${lastId.current}`,
        );
        if (res.ok) absorb(await res.json());
      } catch {
        // A failed poll is not worth telling a visitor about. The next one is
        // four seconds away, and the thing they are waiting for is a person.
      }
    }

    const timer = setInterval(look, POLL_MS);
    return () => {
      stop = true;
      clearInterval(timer);
    };
  }, [embedKey, absorb, status]);

  useEffect(() => {
    foot.current?.scrollIntoView({ block: "end", behavior: "smooth" });
  }, [lines, busy]);

  async function send() {
    const text = draft.trim();
    if (!text || busy) return;

    setDraft("");
    setTrouble(null);
    // Optimistic, and negative ids so it can never collide with a row's. The
    // visitor's own words appearing instantly is the difference between a chat
    // and a form.
    const mine: Line = { id: -Date.now(), who: "you", text, at: new Date().toISOString() };
    setLines((prev) => [...prev, mine]);
    setBusy(true);

    const clientId = messageId();
    try {
      const res = await fetch(`/api/webchat/${encodeURIComponent(embedKey)}`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ token: token.current, text, clientId }),
      });

      if (res.status === 401) {
        // The token expired while the panel sat open. Reloading mints a new one,
        // which is what the visitor would try anyway.
        setTrouble("This conversation timed out. Reload the page to start again.");
        return;
      }
      if (res.status === 429) {
        // A turn for this visitor is already running — they pressed send twice
        // while Belline was thinking. Their message is being answered, so an
        // error would be a lie about the one thing they can see. Say nothing;
        // the poll four seconds away collects the reply.
        return;
      }
      if (!res.ok) {
        setTrouble("That didn't send. Try again in a moment.");
        return;
      }
      absorb(await res.json());
    } catch {
      setTrouble("That didn't send. Try again in a moment.");
    } finally {
      setBusy(false);
    }
  }

  // --- the voice note ------------------------------------------------------

  async function startNote() {
    if (rec.current || busy) return;
    setHint(null);
    setTrouble(null);
    const mime = recordingMime();
    if (!mime) return;

    let stream: MediaStream;
    try {
      stream = await navigator.mediaDevices.getUserMedia({
        audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true },
      });
    } catch {
      setTrouble("The microphone isn't available here — you can type instead.");
      return;
    }
    // The visitor may have let go while the browser was asking permission.
    // A recorder that starts after the finger has gone would run until the
    // sixty-second stop with nobody holding anything.
    if (!holding.current) {
      stream.getTracks().forEach((t) => t.stop());
      return;
    }

    const recorder = new MediaRecorder(stream, { mimeType: mime });
    const entry = {
      recorder,
      stream,
      chunks: [] as Blob[],
      startedAt: Date.now(),
      tick: setInterval(() => setRecording(Math.floor((Date.now() - entry.startedAt) / 1000)), 250),
      stopAt: setTimeout(() => stopNote(), NOTE_MAX_SECONDS * 1000),
      discard: false,
    };
    rec.current = entry;
    recorder.ondataavailable = (e) => {
      if (e.data.size) entry.chunks.push(e.data);
    };
    recorder.onstop = () => {
      clearInterval(entry.tick);
      clearTimeout(entry.stopAt);
      stream.getTracks().forEach((t) => t.stop());
      if (rec.current === entry) rec.current = null;
      setRecording(null);

      const ms = Date.now() - entry.startedAt;
      if (entry.discard) return;
      if (ms < NOTE_MIN_MS) {
        setHint("Hold the microphone to record a voice note.");
        return;
      }
      void sendNote(new Blob(entry.chunks, { type: mime }), Math.max(1, Math.round(ms / 1000)));
    };
    recorder.start();
    setRecording(0);
  }

  function stopNote(discard = false) {
    const entry = rec.current;
    if (!entry) return;
    entry.discard = discard || entry.discard;
    if (entry.recorder.state !== "inactive") entry.recorder.stop();
  }

  /** Whether the pointer is still down on the microphone. */
  const holding = useRef(false);

  async function sendNote(blob: Blob, seconds: number) {
    if (!blob.size) return;
    const mine: Line = {
      id: -Date.now(),
      who: "you",
      text: "",
      at: new Date().toISOString(),
      voice: { seconds, pending: true },
    };
    setLines((prev) => [...prev, mine]);
    setBusy(true);

    const clientId = messageId();
    try {
      const res = await fetch(`/api/webchat/${encodeURIComponent(embedKey)}/voice`, {
        method: "POST",
        headers: {
          "content-type": blob.type,
          "x-visitor-token": token.current,
          "x-client-id": clientId,
          "x-note-seconds": String(seconds),
        },
        body: blob,
      });

      if (res.status === 401) {
        setTrouble("This conversation timed out. Reload the page to start again.");
        return;
      }
      if (res.status === 429) return;
      if (!res.ok) {
        setLines((prev) => prev.filter((l) => l.id !== mine.id));
        setTrouble(
          res.status === 413
            ? "That note was too long to send. Keep it under a minute, or type it."
            : "That didn't send. Try again in a moment.",
        );
        return;
      }

      const payload = (await res.json()) as {
        ok: boolean;
        reason?: string;
        heard?: string;
        messages?: { id: number; sender: string; body: string; createdAt: string }[];
        status?: Status;
        lastId?: number;
      };

      if (!payload.ok || !payload.heard) {
        // No words in it. Nothing was stored, so nothing stays on screen.
        setLines((prev) => prev.filter((l) => l.id !== mine.id));
        setTrouble(
          payload.reason === "empty"
            ? "I couldn't make that out — try again a little closer to the microphone, or type it."
            : "I couldn't hear that just now. Could you type it instead?",
        );
        return;
      }

      // The words Belline heard, in the visitor's own bubble, before the reply.
      setLines((prev) =>
        prev.map((l) => (l.id === mine.id ? { ...l, text: payload.heard!, voice: { seconds } } : l)),
      );
      absorb(payload);
    } catch {
      setLines((prev) => prev.filter((l) => l.id !== mine.id));
      setTrouble("That didn't send. Try again in a moment.");
    } finally {
      setBusy(false);
    }
  }

  const waiting = status === "HANDOFF_REQUESTED";
  const withPerson = status === "HUMAN_ACTIVE";

  return (
    <div className="bl-wrap">
      <style>{CSS}</style>

      <header>
        <span className="bl-mark" aria-hidden="true">
          <Bubble />
        </span>
        <span className="bl-who">
          <strong>{venueName}</strong>
          <em>
            {withPerson
              ? "You're talking to the team"
              : waiting
                ? "Passing you to the team"
                : `${agentName} · replies in seconds`}
          </em>
        </span>
        {voiceHref && (
          <a className="bl-swap" href={voiceHref}>
            Rather talk?
          </a>
        )}
      </header>

      <div className="bl-log" role="log" aria-live="polite">
        <p className="bl-opener">
          Hi — I&rsquo;m {agentName} at {venueName}. Ask me anything, or tell me what you&rsquo;d
          like to book.
        </p>

        {lines.map((l) =>
          l.who === "note" ? (
            <p key={l.id} className="bl-note">
              {l.text}
            </p>
          ) : (
            <div key={l.id} className={`bl-line bl-${l.who}`}>
              <p>
                {l.voice && (
                  <span className="bl-voice">
                    <Mic />
                    {l.voice.pending ? "Voice note · listening…" : `Voice note · ${clock(l.voice.seconds)}`}
                  </span>
                )}
                {l.text}
              </p>
            </div>
          ),
        )}

        {busy && (
          <div className="bl-line bl-them bl-thinking" aria-label="typing">
            <p>
              <i />
              <i />
              <i />
            </p>
          </div>
        )}

        {(waiting || withPerson) && (
          <p className="bl-note">
            Someone from the team is picking this up. Anything you add here will reach them.
          </p>
        )}

        <div ref={foot} />
      </div>

      {trouble && <p className="bl-trouble">{trouble}</p>}
      {hint && !trouble && <p className="bl-hint">{hint}</p>}

      <form
        onSubmit={(e) => {
          e.preventDefault();
          void send();
        }}
      >
        {recording !== null ? (
          // The bar while a note is being held. The textarea is gone: there
          // is one thing happening and this is it.
          <div className="bl-rec" aria-live="polite">
            <i className="bl-rec-dot" aria-hidden="true" />
            <span className="bl-rec-time">{clock(recording)}</span>
            <span className="bl-rec-say">Release to send · slide off to cancel</span>
          </div>
        ) : (
          <textarea
            rows={1}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              // Enter sends, shift+enter breaks the line. The convention every
              // other chat has, and getting it wrong makes the panel feel broken.
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                void send();
              }
            }}
            placeholder="Type your message"
            aria-label="Your message"
            maxLength={1000}
          />
        )}

        {canRecord && !draft.trim() ? (
          // Hold to record. `touch-action: none` in the stylesheet keeps a
          // long press from becoming a scroll or a context menu, and pointer
          // capture keeps the release arriving here wherever the finger went.
          <button
            type="button"
            className={`bl-mic${recording !== null ? " is-on" : ""}`}
            disabled={busy}
            aria-label={recording !== null ? "Recording — release to send" : "Hold to record a voice note"}
            aria-pressed={recording !== null}
            onPointerDown={(e) => {
              if (e.button !== 0 && e.pointerType === "mouse") return;
              e.preventDefault();
              holding.current = true;
              e.currentTarget.setPointerCapture(e.pointerId);
              void startNote();
            }}
            onPointerUp={(e) => {
              holding.current = false;
              const under = document.elementFromPoint(e.clientX, e.clientY);
              // Let go somewhere else: WhatsApp's slide-to-cancel, without
              // the slide animation. The note is thrown away.
              stopNote(!e.currentTarget.contains(under));
            }}
            onPointerCancel={() => {
              holding.current = false;
              stopNote(true);
            }}
            onContextMenu={(e) => e.preventDefault()}
          >
            <Mic />
          </button>
        ) : (
          <button type="submit" disabled={busy || !draft.trim()} aria-label="Send">
            <Send />
          </button>
        )}
      </form>
    </div>
  );
}

/** 7 → "0:07", 65 → "1:05". */
function clock(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s < 10 ? "0" : ""}${s}`;
}

function Mic() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <rect x="9" y="3" width="6" height="11" rx="3" fill="currentColor" />
      <path
        d="M6 11a6 6 0 0 0 12 0M12 17v3M9 20h6"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function messageId(): string {
  // Enough to be unique per visitor's session, which is all the dedup key needs
  // to be — it is scoped to one conversation by the index it lands in.
  return `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * The mark.
 *
 * A bell inside a speech bubble: the same bell as everywhere else, so a visitor
 * who has seen the button knows what opened, in the one shape that says this one
 * is for typing.
 */
function Bubble() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M3 11.2C3 6.9 7.03 3.5 12 3.5s9 3.4 9 7.7c0 4.3-4.03 7.7-9 7.7a11 11 0 0 1-2.4-.26L5.4 20.5l.5-3.2A7.7 7.7 0 0 1 3 11.2Z"
        fill="currentColor"
        opacity=".16"
      />
      <path
        d="M3 11.2C3 6.9 7.03 3.5 12 3.5s9 3.4 9 7.7c0 4.3-4.03 7.7-9 7.7a11 11 0 0 1-2.4-.26L5.4 20.5l.5-3.2A7.7 7.7 0 0 1 3 11.2Z"
        stroke="currentColor"
        strokeWidth="1.4"
        strokeLinejoin="round"
      />
      <circle cx="12" cy="7.3" r="1.05" fill="currentColor" />
      <path d="M8.6 13.2a3.4 3.4 0 0 1 6.8 0Z" fill="currentColor" />
      <rect x="7.7" y="13.9" width="8.6" height="1.4" rx=".7" fill="currentColor" />
    </svg>
  );
}

function Send() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M4 12h13M11.5 6.5 17.5 12l-6 5.5"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/**
 * Scoped by being the only stylesheet on the page.
 *
 * The panel is a whole document inside an iframe, so there is nothing to collide
 * with and no cascade to defend against — which is why these are element
 * selectors rather than a class system that would only exist to look careful.
 */
const CSS = `
/* The panel, on paper.
 *
 * It was ink — a dark window opening out of a light page, which read as a
 * different piece of software borrowed for the occasion. The site is paper,
 * the dashboard is paper, and the one surface a customer's customer sees
 * should be the same material as the page it opens on.
 *
 * The palette is site.css's, value for value: nothing here may drift from the
 * marketing site, because the two are a metre apart on screen.
 */
:root { color-scheme: light }
* { box-sizing: border-box }
html, body { margin: 0; height: 100% }
body { background: #FBF9F5 }

.bl-wrap {
  height: 100dvh;
  display: grid;
  grid-template-rows: auto 1fr auto;
  background: #FBF9F5;
  color: #14110D;
  font: 400 15px/1.55 "Instrument Sans", ui-sans-serif, system-ui, -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
}

.bl-wrap header {
  display: flex;
  align-items: center;
  gap: 11px;
  padding: 14px 16px;
  border-bottom: 1px solid rgba(20,17,13,.1);
  background: #FBF9F5;
}
.bl-mark { display: grid; place-items: center; width: 32px; height: 32px; flex: none;
  border-radius: 999px; background: rgba(138,103,46,.12); color: #8A672E }
.bl-mark svg { width: 19px; height: 19px; display: block }
.bl-who { display: grid; min-width: 0 }
.bl-who strong { font-weight: 600; font-size: 14.5px; letter-spacing: -.01em;
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis }
.bl-who em { font-style: normal; font-size: 12.5px; color: #746C63 }
.bl-swap {
  margin-left: auto; flex: none; color: #8A672E; text-decoration: none;
  font-size: 12.5px; padding: 6px 11px; border-radius: 999px;
  border: 1px solid rgba(138,103,46,.32);
}
.bl-swap:hover { background: rgba(138,103,46,.08) }

.bl-log { overflow-y: auto; padding: 18px 16px 6px; display: grid; align-content: start; gap: 10px }

.bl-opener { margin: 0 0 4px; font-size: 14.5px; color: #4A443C; max-width: 34ch }

.bl-line { display: flex }
.bl-line p {
  margin: 0; padding: 9px 13px; max-width: 84%;
  border-radius: 15px; font-size: 14.5px; white-space: pre-wrap; overflow-wrap: anywhere;
}
/* Das Haus spricht auf Papier, der Besucher in Tinte. Herum wäre es auch
   lesbar — aber die dunkle Blase ist die auffälligere, und auffällig gehört
   dem, was der Besucher gerade selbst getan hat. */
.bl-line.bl-them { justify-content: flex-start }
.bl-line.bl-them p { background: #F0EBE1; color: #14110D; border-bottom-left-radius: 5px }
.bl-line.bl-you { justify-content: flex-end }
.bl-line.bl-you p { background: #14110D; color: #FBF9F5; border-bottom-right-radius: 5px }

.bl-note {
  margin: 2px auto; padding: 6px 12px; font-size: 12.5px; text-align: center;
  color: #746C63; background: rgba(20,17,13,.045); border-radius: 999px;
}

.bl-thinking p { display: flex; gap: 4px; padding: 13px }
.bl-thinking i { width: 5px; height: 5px; border-radius: 999px; background: rgba(20,17,13,.42);
  animation: pulse 1.1s infinite }
.bl-thinking i:nth-child(2) { animation-delay: .15s }
.bl-thinking i:nth-child(3) { animation-delay: .3s }
@keyframes pulse { 0%,60%,100% { opacity: .3 } 30% { opacity: 1 } }

.bl-trouble { margin: 0; padding: 8px 16px; font-size: 13px; color: #A33327 }

.bl-wrap form { display: flex; gap: 8px; align-items: end; padding: 12px 14px 14px;
  border-top: 1px solid rgba(20,17,13,.1); background: #FBF9F5 }
.bl-wrap textarea {
  flex: 1; resize: none; min-height: 42px; max-height: 120px;
  padding: 11px 13px; border-radius: 13px; border: 1px solid rgba(20,17,13,.16);
  background: #fff; color: #14110D; font: inherit; font-size: 14.5px;
}
.bl-wrap textarea::placeholder { color: #8E867C }
/* Der Rahmen des Dashboards legt beim Fokus noch einen blassen Ring auf jedes
   Textfeld. Zusammen mit dem Umriss unten sind das zwei Ringe um dasselbe
   Feld — hier gilt nur der eine. */
.bl-wrap textarea:focus { box-shadow: none; border-color: rgba(20,17,13,.16) }
.bl-wrap textarea:focus-visible, .bl-wrap button:focus-visible, .bl-swap:focus-visible {
  outline: 2px solid #14110D; outline-offset: 2px;
}
.bl-wrap button {
  flex: none; width: 42px; height: 42px; border: 0; border-radius: 13px;
  background: #14110D; color: #FBF9F5; cursor: pointer; display: grid; place-items: center;
}
.bl-wrap button svg { width: 21px; height: 21px }
.bl-wrap button:disabled { opacity: .32; cursor: default }

/* The microphone. Paper with an ink outline while idle — the quieter of the
   two buttons, because typing is what this panel is for — and ink while a
   note is being held, so the state is visible under a thumb. */
.bl-wrap .bl-mic {
  background: #FBF9F5; color: #14110D; border: 1px solid rgba(20,17,13,.22);
  touch-action: none; -webkit-user-select: none; user-select: none;
  -webkit-touch-callout: none;
}
.bl-wrap .bl-mic.is-on { background: #14110D; color: #FBF9F5; border-color: #14110D;
  transform: scale(1.08) }
.bl-wrap .bl-mic svg { width: 20px; height: 20px }

/* The bar in place of the textarea while recording. */
.bl-rec {
  flex: 1; min-height: 42px; display: flex; align-items: center; gap: 10px;
  padding: 0 13px; border-radius: 13px; background: #F0EBE1; font-size: 13.5px;
}
.bl-rec-dot { width: 9px; height: 9px; border-radius: 999px; background: #A33327;
  animation: rec 1s infinite }
@keyframes rec { 0%,100% { opacity: 1 } 50% { opacity: .25 } }
.bl-rec-time { font-variant-numeric: tabular-nums; font-weight: 600; min-width: 34px }
.bl-rec-say { color: #746C63; font-size: 12.5px; white-space: nowrap; overflow: hidden;
  text-overflow: ellipsis }

/* The label on a spoken message. Inside the visitor's ink bubble, so it is
   paper at reduced strength. */
.bl-voice { display: flex; align-items: center; gap: 5px; font-size: 11.5px; opacity: .72;
  margin-bottom: 3px; letter-spacing: .01em }
.bl-voice svg { width: 12px; height: 12px }

.bl-hint { margin: 0; padding: 8px 16px; font-size: 13px; color: #746C63 }

@media (prefers-reduced-motion: reduce) {
  .bl-thinking i { animation: none; opacity: .6 }
  .bl-rec-dot { animation: none }
}
`;
